### ISSUE TITLE
Can't upgrade ziti-console - Ziti Server running on port undefined

### ISSUE THREAD

**Issue by dmuensterer** [openziti/ziti-console#115]
I'm currently running a ziti-console Version from last October and wanted to update today, however after doing so, the console doesn't run anymore.
I've noticed that the server.js script can't find the port number specified in the config file. This is the output:

```Settings {

  edgeControllers: [
    {
      name: 'ZT Console',
      url: 'https://127.0.0.1:8441',
      default: true
    }
  ],
  fabricControllers: []
}
Ziti Server running on port undefined
```
I think root of the problem is that the script tries to load ```~/.ziti/quickstart/zt/ziti/settings.json``` instead of ```~/.ziti/quickstart/zt/ziti-console/assets/data/settings.json``` at some point.
Restoring the old `ziti-console` folder makes the console work again.

**Comment by JeremyTellier** [comment]
We have a new settings file in /assets/data/settings.json where you can set the home location for your persisted settings files now, things like fabricControllers have not existed for some time so this may have been a breaking change. can you try to addd your edgeController to the array there and set update to true to see if it gives you the new settings?

It should be using the old settings though if the update settings value is false.

**Comment by JeremyTellier** [comment]
Fixed in Release 2.6.1

**Comment by dmuensterer** [comment]
Thanks!
Fyi: Another issue I found in upgrading was that after the upgrade, the default protocol was set to http instead of https and therefore another port needed to be accessed in /assets/data/settings.json.

Where is the setting to change whether to use http or https?

**Comment by dovholuknf** [comment]
@JeremyTellier, did the mechanism to enable tls change at all? @dmuensterer, I'll check my own install in a few hours but this used to be controlled by having a cert and key in the same directory as the server.js file, which I believe was the root of the checkout. Depending on how you deployed Zac (from source or from docker), perhaps those links are broken?

That is usually done in step 3 of the Zac "from source" install: https://docs.openziti.io/docs/learn/quickstarts/zac/#cloning-from-github

**Comment by dmuensterer** [comment]
Thanks, jep - that's it. So the sole deployment of the certificates is also the "switch" itself to enable https?

**Comment by dovholuknf** [comment]
At this time, yes I think that's the driver. The presence of the key pair drives TLS enablement.
