### ISSUE TITLE
Option to add description to Identity Role Attributes

### ISSUE THREAD

**Issue by dmuensterer** [openziti/ziti-console#123]
I'd like to request a feature to be able to add descriptions to Identity Role Attributes.
I like the "pill" kind of way of showing Identity Role Attributes when selecting them but a tooltip containing a defined description would be awesome.

Kind of like Microsoft does it in Azure IAM: https://learn.microsoft.com/en-us/azure/role-based-access-control/media/shared/roles-list.png

I have so many Role Attributes to ensure granular access control that it's very hard to keep track of the exact privileges that are implied just by the sole name.

**Comment by dovholuknf** [comment]
right now i don't think there's an API for this to accommodate the ask but i could see how in a larger system with more attributes it might make sense. i'll mention it to the team as well

**Comment by dmuensterer** [comment]
Yes, i figured this is not only a front-end request but found it fitting here best.
Thanks for considering it, would make our life a lot easier as we currently have >30 role attributes

**Comment by JeremyTellier** [comment]
I would probably use tags and custom fields for this one, maybe I should add a feature request for variable tables in the UI so that people could have the tags show their values there. Thanks
