### ISSUE TITLE
log in with token

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#133]
I'd like the option to supply an API session token instead of username/password. I'd use this feature with certificate authentication to obtain the token out-of-band, then paste it in console. This way there's no need to expose the password at all (to trust the console with the password and whatever storage mediums help transmit the password to the console). This also allows me to disable password auth completely.

**Comment by JeremyTellier** [comment]
You can do this, use the query params:

?controller=[CONTROLLER]&session=[SESSION]
