### ISSUE TITLE
Policy overview different to edit view...

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#136]
Then in the overview of authentication policies, the view is this:

![image](https://user-images.githubusercontent.com/9014794/230796436-12dfcb4a-7a81-45c0-a414-a10de18d955e.png)

However, then you edit the policy, it looks like this:
![image](https://user-images.githubusercontent.com/9014794/230796536-7ef4e252-80a3-4fbb-97ea-622bdf3be114.png)

**Comment by JeremyTellier** [comment]
Fixed in Release 2.6.9
