### ISSUE TITLE
download jwt button gets duplicates

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#138]
Four JWT copies downloaded: https://www.youtube.com/live/JqFO92Es2SU?feature=share&t=988

Two copies: 
![console-multi-jwt](https://user-images.githubusercontent.com/1434400/232165341-378cd84a-4c63-40e5-bacd-380d7b26b002.gif)

**Comment by qrkourier** [comment]
Controller: v0.27.9 
ZAC: 2.6.9

**Comment by dovholuknf** [comment]
Same issue reproduced with a brand new install. I got THREE files... :D

**Comment by JeremyTellier** [comment]
Firstly, nice job on the video, secondly, this will be fixed in the 2.7.2 push today
