### ISSUE TITLE
Missing Identity.tags attribute editor, and naming conflict.

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti-console#154]
Currently, adding a `tag` to the list of `TAG CLOUD` results in a `tags` key being added to the `Identity.tags` resource attribute.  Additionally, this has the potential to be confusing since the term `tag` (ZAC tag cloud vs ziti resource tags), which is compounded by the fact `Identity.tags` cannot be directly edited in the console currently.

The following is then done in the API call:

`POST /identities`:

```json
"tags": {
  "tags": "foo,bar"
}
```
![image](https://github.com/openziti/ziti-console/assets/22971615/972cb190-d5fc-4008-90ca-06ca5e59e224)

Recommendation is to at least namespace the key: `tags` => `zac_tags` or `zac_tag_cloud`.

**Comment by JeremyTellier** [comment]
Yes this is expected behavior, you can modify what tag input is available in the Settings > Custom Fields section of ZAC, it was just an example of how the tags can be used for anything.

**Comment by dovholuknf** [comment]
I'm going to re-open this issue. I talked a bit with @sabedevops and I can understand his point. As a consumer of ziti with ZAC, I'm not able to add my own tags. Can we make it so that ZAC has a space for 'zac-related' tags, but i'm still able to add my OWN tags too? I think that'd be really useful and seems in the spirit of the 'tags' idea from the API

**Comment by JeremyTellier** [comment]
@sabedevops Just for reference, you can add custom tags using the Name/Value pairs list, which clint pointed out was not obviously labelled, you can also turn off the "Custom Fields" - ZAC only style tags under personal settings. I am going to label these out better so it stands out.

![image](https://github.com/openziti/ziti-console/assets/56126806/4479d7d0-0e23-400f-b884-0f8ae0643464)

**Comment by sabedevops** [comment]
@JeremyTellier Thanks for the feedback. I was aware of the `Custom Fields` and appreciate your work to make things more clear. I wanted to add that part of the confusion came from having a default where the custom field is added to all resource types which support that attribute.

![image](https://github.com/openziti/ziti-console/assets/22971615/22496fb9-3635-46b3-90df-5ff0ac17156f)

This is probably not the safest default value as you can inadvertently pollute other api resource requests. @dovholuknf and I managed to do it inadvertently while looking at this together. tl;dr people don't read closely enough
