### ISSUE TITLE
Code Fields Scroll to position on change

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/ziti-console#157]

**Comment by chrda81** [comment]
> That sounds annoying, and definitely not what I would expect. :)
Yes that's right. I created a little video.

https://github.com/openziti/ziti-console/assets/36750848/de13f877-b315-4f94-b63e-684708b7c25b

**Comment by JeremyTellier** [comment]
Fixed in 2.9.2 - I don't love my fix though, please let me know if you see this happening anywhere else.

**Comment by chrda81** [comment]
Wow, thanks Jeremy. When will this be released (because only 2.9.0 is shown as downloadable version), or is there a nightly build to try and get back to you?
