### ISSUE TITLE
UI inconsistency

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-console#161]
see report from discourse: https://openziti.discourse.group/t/ui-inconsistency-in-manage-edit-profile/1500

> I noticed a UI Inconsistency in Manage/Edit Profile. Note that the ZAC menu refers to ‘EDIT Profile’ whereas the actual page says ‘MANAGE Profile’.

![image](https://github.com/openziti/ziti-console/assets/46322585/b5d11834-7423-452c-a4e2-cc8c25762e79)

**Comment by JeremyTellier** [comment]
Fixed in 2.8.6
