### ISSUE TITLE
don't crash when attaching to the wrong scheme

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-console#17]
see discourse at https://openziti.discourse.group/t/ziti-console-breaks-when-tryin-to-login-for-first-time/263

right now node is crashing when you supply http to an https endpoint. It shouldn't crash :) It should even maybe tell you "you probably screwed it up" somehow? :)

**Comment by ecelis** [comment]
I did peek at the code, if I wrap the callback in `GetPath` in `server.js` to handle the error I prevent node crashing. Still need to look more to return some sort of error back to the user. Any pointers are welcome.

P.S. I can take over this, but not until weekend.

**Comment by JeremyTellier** [comment]
I pushed up a fix for it, there was a little more to do just to block the ability to ever add an invalid url in the first place, but it was basically what you said with some minor tweaks, thanks for the help!
