### ISSUE TITLE
Errors when editing host.v1 configuration

### ISSUE THREAD

**Issue by mvelbaum** [openziti/ziti-console#173]
I think that this happened after upgrading to v2.9.3. It seems that host.v1 config in the UI now forces me to fill out values for the connect timeout:
![image](https://github.com/openziti/ziti-console/assets/1465262/5ea15e08-9d83-416c-8109-732e6d038a76)

If I set a value using the requested format, the router will complain on startup:
```
ziti-edge-router                  | * 'ListenOptions.ConnectTimeout' expected type 'time.Duration', got unconvertible type 'string', value: '0s'] serviceId=[4ryLLcOB6TGozmLZEaOufl] serviceName=[zac]} service is hostable but unable to decode server config of type host.v1
```

I was able to create a config from the CLI without this though.

**Comment by JeremyTellier** [comment]
I will look into this and get a new release up asap.

**Comment by JeremyTellier** [comment]
Ok, I was on an older controller, this looks like more of a controller issue than a ZAC issue, but I can patch it to use the new controller requirements

**Comment by mvelbaum** [comment]
Thanks! Is it possible to push a new container to docker hub?

**Comment by dovholuknf** [comment]
:latest as well as version 2.9.4 have been published
