### ISSUE TITLE
stop using odd-numbered NodeJS releases

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#233]
Odd-numbered releases are unsupported after six months. Use LTS releases for prod builds.

https://nodejs.org/en/about/previous-releases

**Comment by dovholuknf** [comment]
i'm looking to move away from needing node and running it as a separate server anyway. instead, i want to use the controller to host zac. when we move to that delivery mechanism this will be irrelevant

**Comment by qrkourier** [comment]
Having NodeJS serve the web UI and call the mgmt API is pretty convenient, and it's central to how the K8s deployment works. I can imagine alternatives, and I'd like to know more about the idea of moving away from NodeJS.
