### ISSUE TITLE
ensure only the SPA releases are marked "latest" in GitHub

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#329]
Only the releases for app-ziti-console provide the ziti-console.zip artifact, so it's important that the other releases for ziti-console-lib are never marked latest, or this download one-liner will stop working.

```bash
wget https://github.com/openziti/ziti-console/releases/latest/download/ziti-console.zip
```

This one-liner is extremely helpful for providing a pastable example for documentation and support, not to mention automation, because it replaces the multi-step process of finding and downloading the latest version of app-ziti-console.

**Comment by dovholuknf** [comment]
It's equally passable to tell the user to get "the version they want". This handy link should not be mandated.

**Comment by qrkourier** [comment]
What about robots? It's much easier to script a predictable URL.
