### ISSUE TITLE
verified CA token download button broken

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#337]
After verifying an external CA, I'm unable to download the token. The cert icon is visible, but clicking has no effect.

**Comment by qrkourier** [comment]
regarding feature added in https://github.com/openziti/ziti-console/issues/35

**Comment by rgallettonf** [comment]
Looks like a duplicate issue was opened for this and closed as part of this PR:
https://github.com/openziti/ziti-console/pull/549

Marking this issue as closed.
