### ISSUE TITLE
Make “cancel” option easier to read/standardize

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#34]
Within the GUI webpages, the standard button to cancel out of the screen is a Cancel button. However in ZAC it is a hard to read hyperlink. Can this be standardised back to a button that sticks out.

**Comment by JeremyTellier** [comment]
This was the wrong color, I don't like to over use "buttons", generally I like the main actions to be buttons so I have darkened the text for the next release at least as it should have been.
