### ISSUE TITLE
console fails silently when token expires

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#340]
The SPA does not return to the login prompt or issue a toast or alert when the token expires. Rather, because the controller continues to serve the static files, it appears to be responsive while showing zero entities of any type, and so it degrades non-gracefully in that scenario.

The workaround is to log out and back in.

**Comment by qrkourier** [comment]
@rgallettonf Let me know if you want to co-work on this. I can reproduce it with my test instance.

**Comment by qrkourier** [comment]
![Peek 2024-05-21 09-41 4fps](https://github.com/openziti/ziti-console/assets/1434400/39cdd70e-43e3-4d41-8eb4-795a2d2c8f62)

**Comment by rgallettonf** [comment]
@qrkourier this should make it into the next release of ZAC, or you can verify by building and running locally.
