### ISSUE TITLE
selected sidebar category is broken

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#347]
The currently-selected sidebar category doesn't work. That is, if I use the sidebar to navigate to "Services," then I select a service, I can only navigate to _other_ categories like "Configurations" or "Identities," but not back to the list of services by re-selecting "Services."
![Peek 2024-05-15 18-24](https://github.com/openziti/ziti-console/assets/1434400/4633c3ad-71ac-4a25-92bd-fc22dafa6fe2)

**Comment by qrkourier** [comment]
I confirmed this problem exists in both Node.js server and SPA.

**Comment by rgallettonf** [comment]
This should now be resolved with the implementation of "deep links" so that all new create/edit forms have their own independent route/url

**Comment by rgallettonf** [comment]
@qrkourier give this another try whenever you get a chance, then we can hopefully close. Thanks!

**Comment by qrkourier** [comment]
resolved by app-ziti-console-v3.4.1
