### ISSUE TITLE
Expose "auto" jwt from ZAC

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-console#35]
Steps to reproduce:
* create and validate a 3rd party CA, making sure to enable the CA for auto enrollment:  ![image](https://user-images.githubusercontent.com/46322585/174594804-fe388848-1a09-4777-9851-e2828ebee7af.png)
* Notice that the jwt exists in the API but the ZAC does not provide a mechanism to download the jwt from "https://${ZITI_EDGE_CTRL_ADVERTISED}/edge/management/v1/cas/${CA_ID}/jwt"

**Comment by JeremyTellier** [comment]
Available in 2.6.4
