### ISSUE TITLE
Status of Autoenrollment / OTT etc not displaying on 3rd party CA

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#37]
Currently running Controller: v0.25.13 ZAC: 2.3.4.

I have created a third party CA and verified.  I have flipped some of the toggle options, such as Autoenrollment.  However, when I go and edit the CA, those options are defaulting to off, and not what they should be set to.  Refreshing the main overview page multiple times shows the correct settings, as well as when I export a JWT.

Appears to be a UI issue where when the edit page is rendered, the buttons are not being set to the correct positions.

Example of CA
![image](https://user-images.githubusercontent.com/9014794/175811094-5f1412db-b4f3-4d9c-8bf6-262931721edd.png)

When I go edit, it shows this
![image](https://user-images.githubusercontent.com/9014794/175811104-6c472eae-b09f-4a79-8e29-b25619502ea7.png)

Saving the page will save as per the settings of that page, ie all off.

**Comment by JeremyTellier** [comment]
Fixed in 2.6.4
