### ISSUE TITLE
Unable to login on ZAC and CLI after certain amount of time

### ISSUE THREAD

**Issue by samsoeapp** [openziti/ziti-console#438]
Hi,

We are testing the openziti deployment in our environment so that we can use our computer/laptops to gain access to some resources in our datacenter.
Initially we are using Debian 12 with the QuickStart install method.

This is working perfectly but we notice that for some odd reason after a unknown amount of time we where unable to login with the default admin on both the ZAC and trough the CLI.

So, I rolled back our VM, was able to login again and created 2 extra administrators.

But now, after a couple of days, again i was unable to login trough the default admin.
As we are not in need of this default admin i was satisfied with using the other 2 admins.

But, after a while also one of the admins could not login anymore.

So with the single working admin account i used the cli to change the entry in the updb to change the passwords.
But yet again now all of my 3 admin accounts are locked, ziti is working but I am unable to make any changes...

Also, I noticed that the Default Admin is not using the updb method but it is using the token variant from the get-go.

Anyone else experiencing these kinds of issues?
Am I perhaps doing something that i shouldn't?

**Comment by dovholuknf** [comment]
I'm transferring this issue to ziti-console as I think it's a ziti-console issue. If you can reproduce with the ziti cli alone, I'd be interesting in understanding that. I've never seen this behavior before but restoring the VM does make me wonder if perhaps some PKI was recovered?

When this happens, it'll be helpful to see the "developer tools" console and network views (be careful not to share secrets if you share a screen cap)

**Comment by qrkourier** [comment]
@samsoeapp Thanks for sharing how you're running the console. You're following the BASH quickstart to build and install the console as a Linux systemd service.

There are two modes for running the console:
1. as a standalone Node.js web server (deprecated)
2. as a static, single-page application hosted by the Ziti controller (preferred)

The deployment guides document only the preferred mode: https://openziti.io/docs/category/deployments

**Comment by dovholuknf** [comment]
@qrkourier - I want to stay with the way he's using it now. This just confuses the matter.

**Comment by samsoeapp** [comment]
@qrkourier Thank you for your response. 

You are totally right! I used the deprecated method...

I just setup a debian server in my homelab. Installed a brand spanking new ziti network and took the approach which is described in: https://openziti.io/docs/guides/deployments/linux/console

It is easier to deploy and looks like it working a lot better. I will also deploy this at the office tomorrow and see if the problem persists.

**Comment by samsoeapp** [comment]
Hi,

I have deployed option: 2. as a static, single-page application hosted by the Ziti controller (preferred) 
These are now running on both my homelab and cloudserver. 

I'm contacting the zac site using either: (Which with the old setup worked like a charm)
- https://External-IP:8441/zac
- https://Internal-IP:8441/zac

(I not yet use "https://domainname:8441/zac" as I'm currently getting htst errors and I still have to learn and figure out why that is not working)

When opening the zac webpage and trying to login with my username and password I get the following error:
"Error: Uncaught (in promise): Object: {"error":"Unable to login to selected edge controller - Unauthorized. Please make sure the selected controller is online and accessible"}"
It then also sends me to the page where I can input the controller's name and URL:
![image](https://github.com/user-attachments/assets/d9b2d8e5-44cc-4d2c-a652-db5fd877ffba)

Then when i try to enter the "edge controller name" and "URL" and pressing enter or clicking on the "set controller" button i get no feedback, as in a pop up.

But i do see this on the developer console:
![image](https://github.com/user-attachments/assets/fbfb5302-ab24-4bda-a1b4-e39aac3fd65e)

I have set the following in my config:
    apis:
      # binding - required
      # Specifies an API to bind to this webListener. Built-in APIs are
      #   - edge-management
      #   - edge-client
      #   - fabric-management
      - binding: edge-management
        # options - arg optional/required
        # This section is used to define values that are specified by the API they are associated with.
        # These settings are per API. The example below is for the 'edge-api' and contains both optional values and
        # required values.
        options: { }
      - binding: edge-client
        options: { }
      - binding: fabric
        options: { }
      - binding: zac
        options: { "location": "./zac", "indexFile":"index.html" }

PS: It was quite late yesterday when I tested so I'm not totally sure, as i thought at least on my home lab locally the zac worked and I was able to login.

Also do correct me hardly if i'm talking rubbish, i'm just a microsoft system/network engineer with some linux knowledge trying to learn.

**Comment by samsoeapp** [comment]
Ugh, yet again i have not tested all scenarios.

When i connect from my device at the HQ, either over the VPN-Tunnel or from a server in the same subnet in the datacenter i am able to login using "https://10.10.10.30:8441/zac" and it does not ask me for a edge controller name or URL.

I'm now also quite sure that when i hop onto my home machine i'm also able to connect to the ZAC and straight login into it.

In my previous post i was connected via the tunneler or remotely.

**Comment by samsoeapp** [comment]
Okay, tested some more on both the homelab and datacenter install.

When from a machine i connect to either site using "https://remote-ip:8441/zac" when i first try to login it sends me back to the page where i have to input the edge controller name and URL.
Then when i input a name and as URL "https://remote-ip:8441" i get back to the login page.

I do get some error popups like:
Name and URL required
undefined

and 

Error
Login Failed
Unable to login to selected edge controller - Unauthorized. Please make sure the selected controller is online and accessible

But i'm at least able to login.

**Comment by dovholuknf** [comment]
> when i first try to login it sends me back to the page where i have to input the edge controller name and URL.

in this deployment mode -- that should **never** happen. If you can reproduce that, I'm sure @rgallettonf would be really appreciative! 

thanks for trying it out -- also you're doing great! thanks for giving us this helpful info

**Comment by samsoeapp** [comment]
So, i did some testing. I tried to login and logout, change some colors etc. (Just some basic stuff) a couple of times using this link from my computer at the office:
- https://edge.ziti.domain.com:8441/zac

I think it does not matter right? Connecting using an IP both internal or external or using the domain name on port 8441?!

Firstly today i was unable to login using the default admin, where as this was working yesterday.
When entering no credentials at the login page or the default admin credentials it pops me back to the screen where i have to input the name and url to connect to the correct controller. Also when doing this, sometimes it goes back to the login page and some other times you click on the button to proceed but no actual feedback is presented. (Feedback such as: Controller not available etc.)

So i tried logging in with both of my backup admins which worked at first.
But after a while my first backup admin also not able to login anymore.
Soon after my second backup admin also not able to login anymore.

So at this point of time I'm unable to login with my 3 admin accounts on both zac and using the CLI.

Thus the installation works, for the connected clients etc. But unable to make any changes on both ZAC or CLI.

This is some output of:

CLI:
# Previous attempt:
~# ziti edge login
Using controller url: https://edge.ziti.domain.com:8441/edge/management/v1 from identity 'default' in config file: /root/.config/ziti/ziti-cli.json
Using username: admin from identity 'default' in config file: /root/.config/ziti/ziti-cli.json
Enter password:
error: unable to authenticate to https://edge.ziti.domain.com:8441/edge/management/v1. Status code: 401 Unauthorized, Server returned: {
    "error": {
        "code": "INVALID_AUTH",
        "message": "The authentication request failed",
        "requestId": "35.mHvgS-"
    },
    "meta": {
        "apiEnrollmentVersion": "0.0.1",
        "apiVersion": "0.0.1"
    }
}

# Current attempt:
:~# ziti edge login
Enter controller host[:port] (default localhost:1280): localhost:8441
Enter username: admin
Enter password:
error: unable to authenticate to https://localhost:8441/edge/management/v1. Status code: 401 Unauthorized, Server returned: {
    "error": {
        "code": "INVALID_AUTH",
        "message": "The authentication request failed",
        "requestId": "V.68Hv8V-"
    },
    "meta": {
        "apiEnrollmentVersion": "0.0.1",
        "apiVersion": "0.0.1"
    }
}

ZAC:
# Casual login:
![image](https://github.com/user-attachments/assets/767c5f56-e737-4463-9df3-1aa2e7b3545e)
![image](https://github.com/user-attachments/assets/2ed932b2-b87d-4d21-bffd-09a391cdad6d)

# Trying to add the controller with faulty url, no popup is shown that url is faulty:
![image](https://github.com/user-attachments/assets/9d006235-b626-4624-9e74-ec16bb1ca505)

# Trying to add the controller with good url, no popup is shown that url is faulty:
![image](https://github.com/user-attachments/assets/7d9ba14c-7e8a-40b0-9269-da95cbe9ba0f)

So, I can leave the server like this, and if I want to I can restore a snapshot from where it was working.
What information do you need from me that can help troubleshoot/debug etc.?

**Comment by samsoeapp** [comment]
When on ZAC using the following url: https://10.10.10.30:8441 it does accept and returns to the username and password login page. But unable to login due to the fact that my 3 admin accounts are not able to login anymore.

I do remember that when i was logged in and tried to change the colors, darkmode etc i clicked on the manage account option a couple of times, where it than asks for changing the password. Here i did not change the password but just clicked on the homepage icon for example.

Maybe it has to do something with that?

Also to add, in this deployment of ZAC i was not able to use the big + icon to add new identitys, i was able to add a identity using the button on the left bar.

**Comment by dovholuknf** [comment]
For completeness sake, can you remove zac from the equation and try authenticating with the ziti edge login command?

**Comment by samsoeapp** [comment]
I used this guide to install: https://openziti.io/docs/learn/quickstarts/network/local-no-docker

All the Identity's and configurations of the services i did with ZAC.

I'm running a VM on hyper-v:
Debian GNU/Linux 12 (bookworm)
Kernel: 6.1.0-21-amd64

ZITI VERSION: v1.1.7

I'm going to install a brand-new server with a new network to be certain it is not anything faulty on the deployment side.
But ill (just in case) keep a copy running of the old server if needed some information from that old deployment.

**Comment by dovholuknf** [comment]
To be totally honest, this is really bizzare. I've never seen this behavior and nobody else has reported this behavior either.

If you can help narrow down exact steps to reproduce -- that'd be really amazing. I have a Debian 12 VM on hyper-v right now actually, i'll go through the quickstart and let it simmer there and see what happens. I'm generally using "the latest", but i'll try to get 1.1.7 running to ensure as close a test as possilbe.

Any extra details? Does the VM sleep? do you pause it? does your base OS sleep at all? Do you know how long "a certain amount of time" is? 30 minutes is __USUALLY__ the amount of time as that's the default amount of time a session is good for - so that'd be my guess?

**Comment by samsoeapp** [comment]
Hi @dovholuknf ,

It has been a couple of days now and the new server still working as expected.
Some bugs are present in the "new deployment" of ZAC but i will report these seperatly.

If you want to have some specific logs i can still pull them out of the old server, just let me know when you need those and what exactly you need.

Thanks!

**Comment by dovholuknf** [comment]
I'll go ahead and close this issue then. You can always open it back up if needed. Happy to hear it's been stable for you. 

Nobody could reproduce this issue still so I'm not sure any logs will help to be honest. If you can provide a set of steps to reproduce, that's what would be the most valuable. 

Thanks for following up

**Comment by samsoeapp** [comment]
Hi,

It has been 3 weeks, where my new setup was running great!
After changing and testing a lot using ZAC (new deployment type) all of a sudden, my admin account stopped working. I am unable to login to both zac and the cli using this admin account.

So i tried loggin in the cli with another admin (i have 3 excluding the defaullt admin) and tried changing the password, removing and creating the updb record etc but none of these steps worked.

Commands used:
- ziti edge list authenticators
- ziti edge delete authenticator "ID"
- ziti edge create authenticator updb admin_bla admin_bla  test1234!
- ziti edge update authenticator updb --identity admin_bla

Usually, at least in my old environment, when this was occuring, if i now login with another admin account to ZAC this logged in account would be unusable in about a day.

It is hard to reproduce, but not inpossible. It just takes a while.

The last thing i would like to do, is create a new network where i don't install ZAC to see if i can reproduce.

Steps to reproduce, as far of my knowledge of the issue:
1. Setup a virtual server on hyper-v running debian 12 (just a simple setup)
2. Install openziti using this guide: https://openziti.io/docs/learn/quickstarts/network/local-no-docker
3. Create 3 alt admin accounts (This is for safety purposes if one would fail as a backup)
4. Create 2 identities which we only use on 2 windows machines using the ziti desktop edge app
5. Create 3 services using ZAC

Install script openziti/zac:
```
apt update
apt install -y ufw tar hostname jq curl unzip
apt -y upgrade
export EXTERNAL_DNS="edge.ziti.domain.nl"
export EXTERNAL_IP="$(curl -s eth0.me)"       
export ZITI_CTRL_EDGE_IP_OVERRIDE="${EXTERNAL_IP}"
export ZITI_ROUTER_IP_OVERRIDE="${EXTERNAL_IP}"
export ZITI_CTRL_EDGE_ADVERTISED_ADDRESS="${EXTERNAL_DNS:-${EXTERNAL_IP}}"
export ZITI_ROUTER_ADVERTISED_ADDRESS="${EXTERNAL_DNS:-${EXTERNAL_IP}}"
export ZITI_CTRL_ADVERTISED_PORT=8440
export ZITI_CTRL_EDGE_ADVERTISED_PORT=8441
export ZITI_ROUTER_PORT=8442
export ZITI_ROUTER_LISTENER_BIND_PORT=8444
export ZITI_ROUTER_ROLES=public
source /dev/stdin <<< "$(wget -qO- https://get.openziti.io/ziti-cli-functions.sh)"; expressInstall
createControllerSystemdFile
createRouterSystemdFile "${ZITI_ROUTER_NAME}"
stopRouter 
stopController 
cp "${ZITI_HOME}/${ZITI_CTRL_NAME}.service" /etc/systemd/system/ziti-controller.service
cp "${ZITI_HOME}/${ZITI_ROUTER_NAME}.service" /etc/systemd/system/ziti-router.service
systemctl daemon-reload
systemctl enable --now ziti-controller
systemctl enable --now ziti-router
systemctl -q status ziti-controller --lines=0 --no-pager
systemctl -q status ziti-router --lines=0 --no-pager

zac:
cd ~
wget https://github.com/openziti/ziti-console/releases/latest/download/ziti-console.zip
source ${HOME}/.ziti/quickstart/$(hostname)/$(hostname).env
export ZITI_HOME
unzip -d ${ZITI_HOME}/zac ./ziti-console.zip
# In ${ZITI_HOME}/$(hostname -s).yaml, add a web API binding zac in the list containing edge-management.

      - binding: zac
        options:
          location: ./zac
          indexFile: index.html

nano ${ZITI_HOME}/$(hostname -s).yaml
systemctl restart ziti-controller.service
```

It's really frustrating. We really like the product and using it every day, but this tiny problem makes it unmanageable in the long run.

If I can collect anything or provide some more info, please let me know!!!

**Comment by dovholuknf** [comment]
I can appreciate how frustrating this would be :(... If it were me, I'd have the same exact opinion. this is an utterly unmanageable situation. I know it's of little to no comfort, but you're the only person to ever have this particular situation. My hunch is that the overlay network or the database is getting reinstalled or corrupted somehow. Figuring out exactly how will probably be a challenge. In my opinion, the ZAC is incapable on it's own of affecting this change unless someone is logging in and changing your password without you knowing it... :(

Can you export the full controller log -- or maybe just the amount of logs from just before when it was working to where it was no longer working and send them to me in some way? (google drive, dropbox, whatever)

After that, if you don't mind. I would start backing up the controller database __AT LEAST__ right after you install it or better yet, every day, maybe every hour (depending on how quickly it happens) if you need to.
```
# Run ziti edge db snapshot every hour
0 * * * * /path/to/ziti edge db snapshot

# Run ziti edge db snapshot every day at midnight
0 0 * * * /path/to/ziti edge db snapshot
```

this will clog up the `$ZITI_HOME/db` (or wherever you put it) with backups but the operation is fast.

Once the issue happens again (and here's the part you need to be ok with) you can send us the before/after databases and we can take a look to see what changed. It also would help you narrow the window of time down to when the change occurred.

**Comment by samsoeapp** [comment]
Hi @dovholuknf 

Thanks for responding this quickly.

You've provided some great tips that i would most definitely try, thanks for that!

Hopefully i was smart enough to already have made such a backup and will try to restore it in order to reproduce again.

Also when testing to reproduce i will keep an close eye on the logs and export them immediately after.

When i have these logs collected i will send them to you.
