### ISSUE TITLE
BASE_HREF is wrongly quoted

### ISSUE THREAD

**Issue by jonasgroenke** [openziti/ziti-console#444]
Hey,
after updating to the latest release, the admin ui stopped working because the scripts are loaded from the wrong base url. It tries to load them from `/zac/'/zac/assets/scripts/service.js`. After correcting, it manually in the docker container and removing the double quotes, it works. I'm using the version that is embedded in the controller.

Wrong: `<base href="'/zac/'">`
Correct: `<base href="/zac/">`

I think the problem comes from here:
https://github.com/openziti/ziti-console/blob/app-ziti-console-v3.4.4/.github/workflows/docker-publish.yml#L84

You can use this command to check it :)
`docker run --rm -ti openziti/ziti-console-assets:3.4.4 cat dist/app-ziti-console/index.html`

Kind regards
Jonas

**Comment by rgallettonf** [comment]
@jonasgroenke this should be resolved now with the 3.4.5 releae, if/when you want to give it a try. Let us know if you still are having issues. Thanks!
