### ISSUE TITLE
add linux package

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#448]
~~`apt install openziti-controller` will depend on `openziti-console` so the static files will be available for the typical user to enable the console with less friction.~~

EDIT: just add the package to reduce user friction during install and simplify the deployment logic

**Comment by dovholuknf** [comment]
do not make the controller depend on ziti-console. this is not the right way to do it

**Comment by qrkourier** [comment]
This package represents a convenient way to install the console files as part of the effort to remove prod deployment friction, especially as it relates to installing and configuring the console: https://github.com/openziti/ziti/issues/2311
