### ISSUE TITLE
clicking an attribute on the identities list page leads to a broken route

### ISSUE THREAD

**Issue by mguthrie88** [openziti/ziti-console#466]
Using ZAC version `3.4.5`

Click on any attribute on the Identities list page, and it leads to a stubbed-in "page-not-found works!" component. I suspect the issue is in the route generation. The route changes to this: `/zac/identitiesDz7eGlInc-` which looks like it might be missing a slash. When I click on the same identity's name I get the same route, but with a slash `/zac/identities/Dz7eGlInc-`

**Comment by rgallettonf** [comment]
This should hopefully be resolved in the 3.4.6 release that went out today. If you're still seeing it though after you update I can take another look.

**Comment by rgallettonf** [comment]
Should be resolved as of 3.4.6
