### ISSUE TITLE
Render the Protocol/Hostname/Port details on Advanced Service form using the attached config's

### ISSUE THREAD

**Issue by rgallettonf** [openziti/ziti-console#483]
It would be convenient to have the protocol/hostname/port info extracted from the attached configs and rendered in a pod on the advanced service details page.

**Comment by dovholuknf** [comment]
This is a bit strange. i can understand wanting to be able to copy/paste urls though. the pills as they are -- really are not ergonomic. It's a huge pain to copy from them but i'm not sure this is the right answer. It also seems like it's ONLY going to really work for "host" configs. not binds.... It doesn't work for > 1 intercept, it doesn't work for forward hosts or forwarded ports... 

![image](https://github.com/user-attachments/assets/fcc6f7f7-dc8b-4e68-a286-c9cc586e27b8)

I feel like a smart 'copy summary' type of button is really what's needed here but on the whole i'm not sold on this idea overall

**Comment by rgallettonf** [comment]
Discussed and decided this is not needed at the moment. Will re-open if priorities change.
