### ISSUE TITLE
Config editor: Click the Configurations no Configuration Data load?!

### ISSUE THREAD

**Issue by Jameshclai** [openziti/ziti-console#520]
after click the Configurations , there are no "Configuration Data" ?!
![image](https://github.com/user-attachments/assets/df6bd3ab-a2d7-4a0b-8581-bba0a4364358)

**Comment by dovholuknf** [comment]
So you made a host.v1 config somehow, then went to the configurations and clicked it and it's empty? Can you confirm what version of the ZAC you're using?

**Comment by Jameshclai** [comment]
> So you made a host.v1 config somehow, then went to the configurations and clicked it and it's empty? Can you confirm what version of the ZAC you're using?

Here is the ZAC source that I tested.
[app-ziti-console-v3.6.0] (https://github.com/openziti/ziti-console/releases/tag/app-ziti-console-v3.6.0)

**Comment by rgallettonf** [comment]
Took a look in to this and was having trouble reproducing. Eventually I was able to see the issue by toggling the config data to a json view and then closing/re-opening the editor. I should have a fix that I'll put up for review shortly.
