### ISSUE TITLE
create config with missing required fields gets incomprehensible error

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-console#524]
This incomprehensible error is returned by the API when the console sends an invalid request.

> Must validate "then" as "if" was valid

We're passing that along to the user as an error toast and a misleading mention of "Service" (we're creating a "Config" in this case), but it's unclear what the user can do to resolve the situation.

I noticed this when I tried to create a host.v1 config with v3.5.0 and hadn't specified the allowed protocols. 

We could inform the user this property is required or send a default. The server responds with an HTTP error code BAD REQUEST (400), so that's a hint for the console to suggest the user can correct their inputs. Maybe we could distinguish between 4NN (user error) and 5NN (server error) response codes, e.g., if the server responds 400 then maybe a blue toast indicating something's not right with the request, and a red server error toast meaning there's a problem on the server side.

![image](https://github.com/user-attachments/assets/29216111-4042-4e45-84bc-86adb5f842a9)

The associated HTTP `POST /edge/management/v1/configs` has this body lacking `allowedProtocols`.

```json
{
  "name": "catchall-dns-host",
  "data": {
    "address": "10.244.0.58",
    "port": 53,
    "forwardProtocol": true
  },
  "configTypeId": "NH5p4FpGR",
  "tags": {}
}
```

and got response

```json
{
    "error": {
        "cause": {
            "field": "(root)",
            "reason": "(root) is invalid: (root): Must validate \"then\" as \"if\" was valid",
            "value": "map[address:10.244.0.58 forwardProtocol:true port:53]"
        },
        "code": "COULD_NOT_VALIDATE",
        "message": "The supplied request contains an invalid document or no valid accept content were available, see cause",
        "requestId": "5cOMG7.LC"
    },
    "meta": {
        "apiEnrollmentVersion": "0.0.1",
        "apiVersion": "0.0.1"
    }
}
```

Here's a valid request:

```json
{
  "name": "catchall-dns-host",
  "configTypeId": "NH5p4FpGR",
  "data": {
    "address": "10.244.0.58",
    "port": 53,
    "forwardProtocol": true,
    "allowedProtocols": [
      "tcp",
      "udp"
    ],
    "httpChecks": [],
    "portChecks": []
  },
  "tags": {}
}
```

**Comment by rgallettonf** [comment]
We should now be fully validating the entered config data against the config-type schema, including some improved invalid styling and growler messages.

Should be resolved as part of #562

@qrkourier if this is still an issue re-open and I can take another look.
