### ISSUE TITLE
Document Recipes intended use

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/ziti-console#53]

**Comment by gooseleggs** [comment]
Currently whenever I want to add a new service, I go to Geoff Bearls’ blog (https://blog.openziti.io/free-secure-access-to-nas-from-anywhere?deviceType=desktop), scroll down to the where he has summarized all the commands, copy them out, then start working through the changes.  Normally I modify and do this through the ZAC as this is easy.  A while ago ZAC was getting recipes (templates), however, I don’t really know how to use it.  Can we have a few buttons, like “Local Service”, “Port Forward”, and it has a few fields to fill in, and then it goes and creates all the policies etc.  After that is done, then you can go and modify as required.

For instance, Cloudflare has a page similar to this:
![image](https://user-images.githubusercontent.com/9014794/210643360-43f8a958-bb06-411f-a7cd-d01d5557267f.png)


I understand that there are million permutations as to the options.  However, I seem to just modify the ports, identities and routers.  I am thinking options would be:

Name - prefixed in all names, ie name.bindv1, name.interceptv1, #name-client, #name-server

**Comment by JeremyTellier** [comment]
I am going to include this with the documentation issue, new recipe types coming soon as well. Thanks
