### ISSUE TITLE
[object Object] shown for configuration ports

### ISSUE THREAD

**Issue by dmuensterer** [openziti/ziti-console#54]
When executing the following command, a configuration is created that shows [object Object] as the port number in ziti-console, please see screenshot attached:
`ziti edge create config log.intercept.v1 intercept.v1 '{"protocols":["tcp"],"addresses":["127.0.0.1"], "portRanges":[{"low":4000, "high":4000}]}'`
I assume this is only a display issue of expecting a string instead of an object
<img width="1107" alt="Screenshot 2022-09-28 at 17 31 05" src="https://user-images.githubusercontent.com/46055597/192893013-3c830666-b524-4381-b48d-ffa05b8e431e.png">

**Comment by dovholuknf** [comment]
@JeremyTellier - can you replicate and fix this issue please? thanks!

**Comment by dovholuknf** [comment]
Thanks for the issue @dmuensterer. We'll get that patched up soon. Cheers. Actually - this is maybe a good #hacktoberfest thing too so if someone wants to contribute that, it might be easy enough. I'll label it that way in case

**Comment by JeremyTellier** [comment]
Fixed in Commit #2c3f28a
