### ISSUE TITLE
Automatically remove leading/trailing whitespaces for names of identities, services, service configurations etc.

### ISSUE THREAD

**Issue by dmuensterer** [openziti/ziti-console#58]
It would greatly improve UX if leading and trailing whitespaces for names of identities, service, service configurations etc. would be removed automatically. Especially if copying from e.g. a text editor, there are sometimes trailing/leading whitespaces which aren't noticed before a non-working service.

**Comment by gooseleggs** [comment]
Ditto - was just going to log an issue for this, when I found it already here. I only noticed the issue when I was running some ziti console commands.  Otherwise I would not have known this existed, until I would try and do something in the command line and wonder why it would not work.

**Comment by JeremyTellier** [comment]
Fixed in 2.5.0
