### ISSUE TITLE
Debug info in ZAC

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#60]
It would be cool if there was a debugging information page in ZAC.  I am thinking a "Debugging" type option down the LHS, and then across the top, can be common command that are run in the controller, such as

- ziti edge policy-advisor identities -q
- ziti edge policy-advisor services -q

There are probably more, as I am a beginner with ziti, but when logging notes in discord etc, could make it easier for a beginner.

**Comment by JeremyTellier** [comment]
You can add "debug" to the command line and all service calls will display in stdout.

e.g. node server.js debug

**Comment by gooseleggs** [comment]
Is that inside the web GUI. I am talking about a debit page that shows the output of those commands.

**Comment by dovholuknf** [comment]
@JeremyTellier - see the followup comment. is there any equivalent of policy-advisor in zac yet? we definitely should have it

**Comment by JeremyTellier** [comment]
@dovholuknf - Yes, policy advisor is available when you click an identity and click a service to test.
