### ISSUE TITLE
Fix up error message

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-console#72]
When logging into the controller with incorrect credentials, the title of the error box is incorrect

![image](https://user-images.githubusercontent.com/9014794/208264144-a39fa655-39a8-4636-840b-2ae8a84bcf4a.png)

Basically, just needs the s dropped

**Comment by dovholuknf** [comment]
thanks, PR is at https://github.com/openziti/ziti-console/pull/73/files - @JeremyTellier when you have a second approve and merge?
