### ISSUE TITLE
When screen width is tightened, don't hide the name

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-console#83]
The identity name is hidden when the screen width is < 1000 px. See this cap below. There is ample whitespace still available, yet the name column of the identity is so squished it's almost not visible and finding it to make it wider is hard. Arguably this is "the most important column" and should be the last one to behave like this. Can that get addressed somehow, please?

![image](https://user-images.githubusercontent.com/46322585/214574501-8ba2feef-04f4-4c91-a4d5-acf66f2e6fe9.png)

Related, if i make the name bigger, there's no horizontal scroll bar making the other columns totally disappear:
![image](https://user-images.githubusercontent.com/46322585/214575023-e088d8d2-21ad-4c97-9fe9-1f5346303765.png)

**Comment by JeremyTellier** [comment]
Fixed it 2.7.2 unless you set the width manually
